### ISSUE TITLE
Probe parts show toggle buttons for not-yet-unlocked science experiments

### ISSUE THREAD

**Issue by Gordon-Dry** [linuxgurugamer/PartCommander#11]
As there is only one experiment unlocked yet, the PartCommander UI shows toggle buttons for all experiments which will be unlocked later.

**Comment by linuxgurugamer** [comment]
specific example, please, save file would be useful.
And, if you click those buttons, does the experiment get run?

**Comment by Gordon-Dry** [comment]
I can try that, but I did not last time as I just was in the mood to play the mission instead of crashing the game  XD

**Comment by Gordon-Dry** [comment]
It happens nothing, the next nearby the button does not toggle and there is nothing logged.

So it's somehow™ okay.
