### ISSUE TITLE
Localization strings in part window

### ISSUE THREAD

**Issue by KSAMissionCtrl** [linuxgurugamer/PartCommander#3]
When accessing an individual part, there are bare localization strings displayed in the labels for some fields and actions

**Comment by linuxgurugamer** [comment]
picture would be helpful, please

**Comment by KSAMissionCtrl** [comment]
you can't reproduce? I'll try to remember to grab one next time I play

It's the same kind of issue as what was going on with Action Groups Extended

**Comment by linuxgurugamer** [comment]
No, I don't have time right now.

**Comment by linuxgurugamer** [comment]
This will be fixed in the 1.4.1 release
